/**
 * p5.js のグローバル変数の定義
 * ESLint の globals 設定に使用します。
 */
export const p5Globals = {
  // 基本的なライフサイクル関数
  setup: 'readonly',
  draw: 'readonly',
  preload: 'readonly',

  // システム変数
  width: 'readonly',
  height: 'readonly',
  drawingContext: 'readonly',
  windowWidth: 'readonly',
  windowHeight: 'readonly',
  focused: 'readonly',
  frameCount: 'readonly',
  frameRate: 'readonly',

  // キャンバス・環境
  createCanvas: 'readonly',
  resizeCanvas: 'readonly',
  noCanvas: 'readonly',
  background: 'readonly',
  clear: 'readonly',
  colorMode: 'readonly',
  fill: 'readonly',
  noFill: 'readonly',
  stroke: 'readonly',
  noStroke: 'readonly',
  strokeWeight: 'readonly',

  // 形状
  arc: 'readonly',
  ellipse: 'readonly',
  line: 'readonly',
  point: 'readonly',
  quad: 'readonly',
  rect: 'readonly',
  triangle: 'readonly',
  beginShape: 'readonly',
  vertex: 'readonly',
  endShape: 'readonly',
  curveVertex: 'readonly',
  bezierVertex: 'readonly',

  // テキスト
  text: 'readonly',
  textAlign: 'readonly',
  textSize: 'readonly',
  textFont: 'readonly',
  textLeading: 'readonly',
  textStyle: 'readonly',
  textWidth: 'readonly',
  textAscent: 'readonly',
  textDescent: 'readonly',

  // 座標変換
  push: 'readonly',
  pop: 'readonly',
  translate: 'readonly',
  rotate: 'readonly',
  scale: 'readonly',
  applyMatrix: 'readonly',
  resetMatrix: 'readonly',

  // マウス
  mouseX: 'readonly',
  mouseY: 'readonly',
  pmouseX: 'readonly',
  pmouseY: 'readonly',
  winMouseX: 'readonly',
  winMouseY: 'readonly',
  pwinMouseX: 'readonly',
  pwinMouseY: 'readonly',
  mouseButton: 'readonly',
  mouseIsPressed: 'readonly',
  mousePressed: 'readonly',
  mouseReleased: 'readonly',
  mouseClicked: 'readonly',
  doubleClicked: 'readonly',
  mouseWheel: 'readonly',
  mouseMoved: 'readonly',
  mouseDragged: 'readonly',

  // キーボード
  keyIsPressed: 'readonly',
  key: 'readonly',
  keyCode: 'readonly',
  keyPressed: 'readonly',
  keyReleased: 'readonly',
  keyTyped: 'readonly',
  keyIsDown: 'readonly',

  // 数学
  abs: 'readonly',
  ceil: 'readonly',
  constrain: 'readonly',
  dist: 'readonly',
  exp: 'readonly',
  floor: 'readonly',
  lerp: 'readonly',
  log: 'readonly',
  mag: 'readonly',
  map: 'readonly',
  max: 'readonly',
  min: 'readonly',
  norm: 'readonly',
  pow: 'readonly',
  round: 'readonly',
  sq: 'readonly',
  sqrt: 'readonly',
  noise: 'readonly',
  random: 'readonly',
  randomSeed: 'readonly',
  randomGaussian: 'readonly',
  sin: 'readonly',
  cos: 'readonly',
  tan: 'readonly',
  asin: 'readonly',
  acos: 'readonly',
  atan: 'readonly',
  atan2: 'readonly',
  degrees: 'readonly',
  radians: 'readonly',

  // 定数
  PI: 'readonly',
  HALF_PI: 'readonly',
  QUARTER_PI: 'readonly',
  TWO_PI: 'readonly',
  TAU: 'readonly',
  DEGREES: 'readonly',
  RADIANS: 'readonly',
  CORNER: 'readonly',
  CORNERS: 'readonly',
  CENTER: 'readonly',
  RADIUS: 'readonly',
  LEFT: 'readonly',
  RIGHT: 'readonly',
  TOP: 'readonly',
  BOTTOM: 'readonly',
  BASELINE: 'readonly',
  POINTS: 'readonly',
  LINES: 'readonly',
  TRIANGLES: 'readonly',
  TRIANGLE_FAN: 'readonly',
  TRIANGLE_STRIP: 'readonly',
  QUADS: 'readonly',
  QUAD_STRIP: 'readonly',
  CLOSE: 'readonly',

  // UI・DOM
  createSlider: 'readonly',
  createButton: 'readonly',
  createCheckbox: 'readonly',
  createInput: 'readonly',
  createRadio: 'readonly',
  createSelect: 'readonly',
  createColorPicker: 'readonly',
  createElement: 'readonly'
};
